version: '3.8'

services:
    db:
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: wallet_db
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d wallet_db"]
            interval: 5s
            timeout: 5s
            retries: 5


    web:
        build: .
        volumes:
            - .:/app # Проброс текущей директории app в контейнер
        ports:
            - "8000:8000"
        environment:
            - DATABASE-URL=postgresql+asyncpg://postgres:password@db:5432/wallet_db
        depends_on:
            db:
                condition: service_healthy
